# This file includes a Wordpress server and its dependencies on LEMP stack.
version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      
  webserver:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/certbot --email info@<domain name> --agree-tos --no-eff-email --staging -d wesupported.com -d www.wesupported.com

  volumes:
    certbot-etc:
    wordpress-data:
    db-data:

  networks:
    worpress-network:
      driver: bridge

