# This file includes a Wordpress server and its dependencies.
version: '3.8'

# Volumes definition
volumes:
  mysql-volume:
  wordpress-html-volume:
  wordpress-etc-apache2-volume:
  wordpress-etc-letsencrypt-volume:

# Networks definition
networks:
  internal-network:
    driver_opts:
      com.docker.network.expose.ports: "false"
  external-network:
    driver_opts:
      com.docker.network.expose.ports: "true"
  no-network:
    driver: none

# Services definition
services:
  mysql:
    extends:
      service: mysql-service
      file: mysql/compose.yml
    env_file: .env
    networks:
      - internal-network

  wordpress:
    extends:
      service: wordpress-service
      file: wordpress/compose.yml
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    volumes:
      - ./src/themes:/var/www/html/wp-content/themes/
    networks:
      - internal-network
      - external-network
