services:
  wordpress-service:
    image: wordpress:6.4.3-php8.2-apache # change it to fpm later
    container_name: wordpress-container
    restart: unless-stopped
    env_file:
      - .env
    # Don't expose the port here. This is a template for this service.
    volumes:
      - wordpress-html-volume:/var/www/html
      - wordpress-etc-apache2-volume:/etc/apache2

volumes:
  wordpress-html-volume:
  wordpress-etc-apache2-volume: