services:
  wordpress-service:
    image: wordpress:latest
    container_name: wordpress-container
    restart: unless-stopped
    env_file:
      - .env
    # Don't expose the port here. This is a template for this service.
    volumes:
      - wordpress-html-volume:/var/www/html


volumes:
  wordpress-html-volume: