services:
  wordpress-service:
    image: wordpress:6.4.3-php8.2-apache # change it to fpm later
    container_name: wordpress-container
    restart: unless-stopped
    env_file:
      - .env
    # Don't expose the port here. This is a template for this service.
    volumes:
      - wordpress-html-volume:/var/www/html
    command: |
      sh -c "snap install --classic certbot";
      sh -c "ln -s /snap/bin/certbot /usr/bin/certbot";
      sh -c "certbot --apache";
      sh -c "while :; do sleep 24h & wait $${!}; certbot renew; done & apachectl -D FOREGROUND";

volumes:
  wordpress-html-volume: