services:
  postgres-service:
    image: "postgres:15.2-alpine3.17" # use 15.2 official postgres version on latest version of alpine linux
    container_name: "postgres-container"
    restart: unless-stopped
    env_file:
      - .env # See all the environment variables of postgres
    # ports: # expose ports in the main compose file. Don't expose ports here.
    #   - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data/ # persist data even if container shuts down
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres-volume: